/**
 * TABLA 5 - CÓDIGO DE PAÍS
 * Manual Técnico de Generalidades sobre Estructuras de Datos Codificación - Tablas
 * Fecha Actualización: 17/02/2022 - Versión: 13.3
 * Superintendencia de Bancos del Ecuador
 * 
 * NOTA: LA TABLA 5 APLICA ISO-3166
 */

export interface Tabla5CodigoPais {
  codigo: string;
  descripcion: string;
}

export const TABLA_5_CODIGO_PAIS: Tabla5CodigoPais[] = [
  { codigo: 'AD', descripcion: 'Andorra' },
  { codigo: 'AE', descripcion: 'Emiratos Árabes Unidos' },
  { codigo: 'AF', descripcion: 'Afganistán' },
  { codigo: 'AG', descripcion: 'Antigua y Barbuda' },
  { codigo: 'AI', descripcion: 'Anguila' },
  { codigo: 'AL', descripcion: 'Albania' },
  { codigo: 'AM', descripcion: 'Armenia' },
  { codigo: 'AN', descripcion: 'Antillas Neerlandesas' },
  { codigo: 'AO', descripcion: 'Angola' },
  { codigo: 'AQ', descripcion: 'Antártida' },
  { codigo: 'AR', descripcion: 'Argentina' },
  { codigo: 'AS', descripcion: 'Samoa Americana' },
  { codigo: 'AT', descripcion: 'Austria' },
  { codigo: 'AU', descripcion: 'Australia' },
  { codigo: 'AW', descripcion: 'Aruba' },
  { codigo: 'AX', descripcion: 'Åland' },
  { codigo: 'AZ', descripcion: 'Azerbaiyán' },
  { codigo: 'BA', descripcion: 'Bosnia y Herzegovina' },
  { codigo: 'BB', descripcion: 'Barbados' },
  { codigo: 'BD', descripcion: 'Bangladesh' },
  { codigo: 'BE', descripcion: 'Bélgica' },
  { codigo: 'BF', descripcion: 'Burkina Faso' },
  { codigo: 'BG', descripcion: 'Bulgaria' },
  { codigo: 'BH', descripcion: 'Bahréin' },
  { codigo: 'BI', descripcion: 'Burundi' },
  { codigo: 'BJ', descripcion: 'Benín' },
  { codigo: 'BL', descripcion: 'San Bartolomé' },
  { codigo: 'BM', descripcion: 'Bermudas' },
  { codigo: 'BN', descripcion: 'Brunéi' },
  { codigo: 'BO', descripcion: 'Bolivia' },
  { codigo: 'BQ', descripcion: 'Bonaire, Saba y San Eustaquio' },
  { codigo: 'BR', descripcion: 'Brasil' },
  { codigo: 'BS', descripcion: 'Bahamas' },
  { codigo: 'BT', descripcion: 'Bután' },
  { codigo: 'BV', descripcion: 'Isla Bouvet' },
  { codigo: 'BW', descripcion: 'Botsuana' },
  { codigo: 'BY', descripcion: 'Bielorrusia' },
  { codigo: 'BZ', descripcion: 'Belice' },
  { codigo: 'CA', descripcion: 'Canadá' },
  { codigo: 'CC', descripcion: 'Islas Cocos' },
  { codigo: 'CD', descripcion: 'República Democrática del Congo' },
  { codigo: 'CF', descripcion: 'República Centroafricana' },
  { codigo: 'CG', descripcion: 'República del Congo' },
  { codigo: 'CH', descripcion: 'Suiza' },
  { codigo: 'CI', descripcion: 'Costa de Marfil' },
  { codigo: 'CK', descripcion: 'Islas Cook' },
  { codigo: 'CL', descripcion: 'Chile' },
  { codigo: 'CM', descripcion: 'Camerún' },
  { codigo: 'CN', descripcion: 'China' },
  { codigo: 'CO', descripcion: 'Colombia' },
  { codigo: 'CR', descripcion: 'Costa Rica' },
  { codigo: 'CU', descripcion: 'Cuba' },
  { codigo: 'CV', descripcion: 'Cabo Verde' },
  { codigo: 'CW', descripcion: 'Curazao' },
  { codigo: 'CX', descripcion: 'Isla de Navidad' },
  { codigo: 'CY', descripcion: 'Chipre' },
  { codigo: 'CZ', descripcion: 'República Checa' },
  { codigo: 'DE', descripcion: 'Alemania' },
  { codigo: 'DJ', descripcion: 'Yibuti' },
  { codigo: 'DK', descripcion: 'Dinamarca' },
  { codigo: 'DM', descripcion: 'Dominica' },
  { codigo: 'DO', descripcion: 'República Dominicana' },
  { codigo: 'DZ', descripcion: 'Argelia' },
  { codigo: 'EC', descripcion: 'Ecuador' },
  { codigo: 'EE', descripcion: 'Estonia' },
  { codigo: 'EG', descripcion: 'Egipto' },
  { codigo: 'EH', descripcion: 'Sahara Occidental' },
  { codigo: 'ER', descripcion: 'Eritrea' },
  { codigo: 'ES', descripcion: 'España' },
  { codigo: 'ET', descripcion: 'Etiopía' },
  { codigo: 'EU', descripcion: 'Unión Europea' },
  { codigo: 'FI', descripcion: 'Finlandia' },
  { codigo: 'FJ', descripcion: 'Fiyi' },
  { codigo: 'FK', descripcion: 'Islas Malvinas' },
  { codigo: 'FM', descripcion: 'Micronesia' },
  { codigo: 'FO', descripcion: 'Islas Feroe' },
  { codigo: 'FR', descripcion: 'Francia' },
  { codigo: 'GA', descripcion: 'Gabón' },
  { codigo: 'GB', descripcion: 'Reino Unido (Inglaterra)' },
  { codigo: 'GD', descripcion: 'Granada' },
  { codigo: 'GE', descripcion: 'Georgia' },
  { codigo: 'GF', descripcion: 'Guayana Francesa' },
  { codigo: 'GG', descripcion: 'Guernsey' },
  { codigo: 'GH', descripcion: 'Ghana' },
  { codigo: 'GI', descripcion: 'Gibraltar' },
  { codigo: 'GL', descripcion: 'Groenlandia' },
  { codigo: 'GM', descripcion: 'Gambia' },
  { codigo: 'GN', descripcion: 'Guinea' },
  { codigo: 'GP', descripcion: 'Guadalupe' },
  { codigo: 'GQ', descripcion: 'Guinea Ecuatorial' },
  { codigo: 'GR', descripcion: 'Grecia' },
  { codigo: 'GS', descripcion: 'Islas Georgias del Sur y Sandwich del Sur' },
  { codigo: 'GT', descripcion: 'Guatemala' },
  { codigo: 'GU', descripcion: 'Guam' },
  { codigo: 'GW', descripcion: 'Guinea-Bissau' },
  { codigo: 'GY', descripcion: 'Guyana' },
  { codigo: 'HK', descripcion: 'Hong Kong' },
  { codigo: 'HM', descripcion: 'Islas Heard y McDonald' },
  { codigo: 'HN', descripcion: 'Honduras' },
  { codigo: 'HR', descripcion: 'Croacia' },
  { codigo: 'HT', descripcion: 'Haití' },
  { codigo: 'HU', descripcion: 'Hungría' },
  { codigo: 'ID', descripcion: 'Indonesia' },
  { codigo: 'IE', descripcion: 'Irlanda' },
  { codigo: 'IL', descripcion: 'Israel' },
  { codigo: 'IM', descripcion: 'Isla de Man' },
  { codigo: 'IN', descripcion: 'India' },
  { codigo: 'IO', descripcion: 'Territorio Británico del Océano Índico' },
  { codigo: 'IQ', descripcion: 'Iraq' },
  { codigo: 'IR', descripcion: 'Irán' },
  { codigo: 'IS', descripcion: 'Islandia' },
  { codigo: 'IT', descripcion: 'Italia' },
  { codigo: 'JE', descripcion: 'Jersey' },
  { codigo: 'JM', descripcion: 'Jamaica' },
  { codigo: 'JO', descripcion: 'Jordania' },
  { codigo: 'JP', descripcion: 'Japón' },
  { codigo: 'KE', descripcion: 'Kenia' },
  { codigo: 'KG', descripcion: 'Kirguistán' },
  { codigo: 'KH', descripcion: 'Camboya' },
  { codigo: 'KI', descripcion: 'Kiribati' },
  { codigo: 'KM', descripcion: 'Comoras' },
  { codigo: 'KN', descripcion: 'San Cristóbal y Nieves' },
  { codigo: 'KP', descripcion: 'Corea del Norte' },
  { codigo: 'KR', descripcion: 'Corea del Sur' },
  { codigo: 'KW', descripcion: 'Kuwait' },
  { codigo: 'KY', descripcion: 'Islas Caimán' },
  { codigo: 'KZ', descripcion: 'Kazajistán' },
  { codigo: 'LA', descripcion: 'Laos' },
  { codigo: 'LB', descripcion: 'Líbano' },
  { codigo: 'LC', descripcion: 'Santa Lucía' },
  { codigo: 'LI', descripcion: 'Liechtenstein' },
  { codigo: 'LK', descripcion: 'Sri Lanka' },
  { codigo: 'LR', descripcion: 'Liberia' },
  { codigo: 'LS', descripcion: 'Lesoto' },
  { codigo: 'LT', descripcion: 'Lituania' },
  { codigo: 'LU', descripcion: 'Luxemburgo' },
  { codigo: 'LV', descripcion: 'Letonia' },
  { codigo: 'LY', descripcion: 'Libia' },
  { codigo: 'MA', descripcion: 'Marruecos' },
  { codigo: 'MC', descripcion: 'Mónaco' },
  { codigo: 'MD', descripcion: 'Moldavia' },
  { codigo: 'ME', descripcion: 'Montenegro' },
  { codigo: 'MF', descripcion: 'San Martin' },
  { codigo: 'MG', descripcion: 'Madagascar' },
  { codigo: 'MH', descripcion: 'Islas Marshall' },
  { codigo: 'MK', descripcion: 'Macedonia' },
  { codigo: 'ML', descripcion: 'Malí' },
  { codigo: 'MM', descripcion: 'Birmania' },
  { codigo: 'MN', descripcion: 'Mongolia' },
  { codigo: 'MO', descripcion: 'Macao' },
  { codigo: 'MP', descripcion: 'Islas Marianas del Norte' },
  { codigo: 'MQ', descripcion: 'Martinica' },
  { codigo: 'MR', descripcion: 'Mauritania' },
  { codigo: 'MS', descripcion: 'Montserrat' },
  { codigo: 'MT', descripcion: 'Malta' },
  { codigo: 'MU', descripcion: 'Mauricio' },
  { codigo: 'MV', descripcion: 'Maldivas' },
  { codigo: 'MW', descripcion: 'Malaui' },
  { codigo: 'MX', descripcion: 'México' },
  { codigo: 'MY', descripcion: 'Malasia' },
  { codigo: 'MZ', descripcion: 'Mozambique' },
  { codigo: 'NA', descripcion: 'Namibia' },
  { codigo: 'NC', descripcion: 'Nueva Caledonia' },
  { codigo: 'NE', descripcion: 'Níger' },
  { codigo: 'NF', descripcion: 'Norfolk' },
  { codigo: 'NG', descripcion: 'Nigeria' },
  { codigo: 'NI', descripcion: 'Nicaragua' },
  { codigo: 'NL', descripcion: 'Países Bajos (Holanda)' },
  { codigo: 'NO', descripcion: 'Noruega' },
  { codigo: 'NP', descripcion: 'Nepal' },
  { codigo: 'NR', descripcion: 'Nauru' },
  { codigo: 'NU', descripcion: 'Niue' },
  { codigo: 'NZ', descripcion: 'Nueva Zelanda' },
  { codigo: 'OM', descripcion: 'Omán' },
  { codigo: 'PA', descripcion: 'Panamá' },
  { codigo: 'PE', descripcion: 'Perú' },
  { codigo: 'PF', descripcion: 'Polinesia Francesa' },
  { codigo: 'PG', descripcion: 'Papúa Nueva Guinea' },
  { codigo: 'PH', descripcion: 'Filipinas' },
  { codigo: 'PK', descripcion: 'Pakistán' },
  { codigo: 'PL', descripcion: 'Polonia' },
  { codigo: 'PM', descripcion: 'San Pedro y Miquelón' },
  { codigo: 'PN', descripcion: 'Islas Pitcairn' },
  { codigo: 'PR', descripcion: 'Puerto Rico' },
  { codigo: 'PS', descripcion: 'Territorios palestinos' },
  { codigo: 'PT', descripcion: 'Portugal' },
  { codigo: 'PW', descripcion: 'Palaos' },
  { codigo: 'PY', descripcion: 'Paraguay' },
  { codigo: 'QA', descripcion: 'Qatar' },
  { codigo: 'RE', descripcion: 'Reunión' },
  { codigo: 'RO', descripcion: 'Rumania' },
  { codigo: 'RS', descripcion: 'Serbia' },
  { codigo: 'RU', descripcion: 'Rusia' },
  { codigo: 'RW', descripcion: 'Ruanda' },
  { codigo: 'SA', descripcion: 'Arabia Saudita' },
  { codigo: 'SB', descripcion: 'Islas Salomón' },
  { codigo: 'SC', descripcion: 'Seychelles' },
  { codigo: 'SD', descripcion: 'Sudán' },
  { codigo: 'SE', descripcion: 'Suecia' },
  { codigo: 'SG', descripcion: 'Singapur' },
  { codigo: 'SH', descripcion: 'Santa Helena' },
  { codigo: 'SI', descripcion: 'Eslovenia' },
  { codigo: 'SJ', descripcion: 'Svalbard y Jan Mayen' },
  { codigo: 'SK', descripcion: 'Eslovaquia' },
  { codigo: 'SL', descripcion: 'Sierra Leona' },
  { codigo: 'SM', descripcion: 'San Marino' },
  { codigo: 'SN', descripcion: 'Senegal' },
  { codigo: 'SO', descripcion: 'Somalia' },
  { codigo: 'SR', descripcion: 'Surinam' },
  { codigo: 'ST', descripcion: 'Santo Tomé y Príncipe' },
  { codigo: 'SU', descripcion: 'Unión Soviética' },
  { codigo: 'SV', descripcion: 'El Salvador' },
  { codigo: 'SY', descripcion: 'Siria' },
  { codigo: 'SZ', descripcion: 'Suazilandia' },
  { codigo: 'TC', descripcion: 'Islas Turcas y Caicos' },
  { codigo: 'TD', descripcion: 'Chad' },
  { codigo: 'TF', descripcion: 'Territorios Australes Franceses' },
  { codigo: 'TG', descripcion: 'Togo' },
  { codigo: 'TH', descripcion: 'Tailandia' },
  { codigo: 'TJ', descripcion: 'Tayikistán' },
  { codigo: 'TK', descripcion: 'Tokelau' },
  { codigo: 'TL', descripcion: 'Timor Oriental' },
  { codigo: 'TM', descripcion: 'Turkmenistán' },
  { codigo: 'TN', descripcion: 'Túnez' },
  { codigo: 'TO', descripcion: 'Tonga' },
  { codigo: 'TR', descripcion: 'Turquía' },
  { codigo: 'TT', descripcion: 'Trinidad y Tobago' },
  { codigo: 'TV', descripcion: 'Tuvalu' },
  { codigo: 'TW', descripcion: 'Taiwán' },
  { codigo: 'TZ', descripcion: 'Tanzania' },
  { codigo: 'UA', descripcion: 'Ucrania' },
  { codigo: 'UG', descripcion: 'Uganda' },
  { codigo: 'UM', descripcion: 'Islas ultramarinas de Estados Unidos' },
  { codigo: 'US', descripcion: 'Estados Unidos' },
  { codigo: 'UY', descripcion: 'Uruguay' },
  { codigo: 'UZ', descripcion: 'Uzbekistán' },
  { codigo: 'VA', descripcion: 'Ciudad del Vaticano' },
  { codigo: 'VC', descripcion: 'San Vicente y las Granadinas' },
  { codigo: 'VE', descripcion: 'Venezuela' },
  { codigo: 'VG', descripcion: 'Islas Vírgenes Británicas' },
  { codigo: 'VI', descripcion: 'Islas Vírgenes Estadounidenses' },
  { codigo: 'VN', descripcion: 'Vietnam' },
  { codigo: 'VU', descripcion: 'Vanuatu' },
  { codigo: 'WF', descripcion: 'Wallis y Futuna' },
  { codigo: 'WS', descripcion: 'Samoa' },
  { codigo: 'YE', descripcion: 'Yemen' },
  { codigo: 'YT', descripcion: 'Mayotte' },
  { codigo: 'ZA', descripcion: 'Sudáfrica' },
  { codigo: 'ZM', descripcion: 'Zambia' },
  { codigo: 'ZW', descripcion: 'Zimbabue' },
  { codigo: 'XK', descripcion: 'Kosovo' }
];