/**
 * Tabla 9 - Código de Nacionalidad
 * Manual Técnico de Generalidades sobre Estructuras de Datos Codificación - Tablas
 * Fecha Actualización: 17/02/2022 - Versión: 13.3
 * *TABLA MIGRADA DE ACUERDO A LA ISO-3166-1
 */

export interface Tabla9Nacionalidad {
  codigo: string;
  descripcion: string;
}

export const TABLA_9_NACIONALIDAD: Tabla9Nacionalidad[] = [
  { codigo: 'A', descripcion: 'A' },
  { codigo: 'AFG', descripcion: 'Afganistán' },
  { codigo: 'ALA', descripcion: 'Åland' },
  { codigo: 'ALB', descripcion: 'Albania' },
  { codigo: 'DEU', descripcion: 'Alemania' },
  { codigo: 'AND', descripcion: 'Andorra' },
  { codigo: 'AGO', descripcion: 'Angola' },
  { codigo: 'AIA', descripcion: 'Anguila' },
  { codigo: 'ATA', descripcion: 'Antártida' },
  { codigo: 'ATG', descripcion: 'Antigua y Barbuda' },
  { codigo: 'ANT', descripcion: 'Antillas Neerlandesas' },
  { codigo: 'SAU', descripcion: 'Arabia Saudita' },
  { codigo: 'DZA', descripcion: 'Argelia' },
  { codigo: 'ARG', descripcion: 'Argentina' },
  { codigo: 'ARM', descripcion: 'Armenia' },
  { codigo: 'ABW', descripcion: 'Aruba' },
  { codigo: 'AUS', descripcion: 'Australia' },
  { codigo: 'AUT', descripcion: 'Austria' },
  { codigo: 'AZE', descripcion: 'Azerbaiyán' },
  { codigo: 'B', descripcion: 'B' },
  { codigo: 'BHS', descripcion: 'Bahamas' },
  { codigo: 'BHR', descripcion: 'Bahréin' },
  { codigo: 'BGD', descripcion: 'Bangladesh' },
  { codigo: 'BRB', descripcion: 'Barbados' },
  { codigo: 'BEL', descripcion: 'Bélgica' },
  { codigo: 'BLZ', descripcion: 'Belice' },
  { codigo: 'BEN', descripcion: 'Benín' },
  { codigo: 'BMU', descripcion: 'Bermudas' },
  { codigo: 'BLR', descripcion: 'Bielorrusia' },
  { codigo: 'MMR', descripcion: 'Birmania' },
  { codigo: 'BOL', descripcion: 'Bolivia' },
  { codigo: 'BIH', descripcion: 'Bosnia y Herzegovina' },
  { codigo: 'BWA', descripcion: 'Botsuana' },
  { codigo: 'BVT', descripcion: 'Isla Bouvet' },
  { codigo: 'BRA', descripcion: 'Brasil' },
  { codigo: 'BRN', descripcion: 'Brunéi' },
  { codigo: 'BGR', descripcion: 'Bulgaria' },
  { codigo: 'BFA', descripcion: 'Burkina Faso' },
  { codigo: 'BDI', descripcion: 'Burundi' },
  { codigo: 'BTN', descripcion: 'Bután' },
  { codigo: 'C', descripcion: 'C' },
  { codigo: 'CPV', descripcion: 'Cabo Verde' },
  { codigo: 'CYM', descripcion: 'Islas Caimán' },
  { codigo: 'KHM', descripcion: 'Camboya' },
  { codigo: 'CMR', descripcion: 'Camerún' },
  { codigo: 'CAN', descripcion: 'Canadá' },
  { codigo: 'CAF', descripcion: 'República Centroafricana' },
  { codigo: 'TCD', descripcion: 'Chad' },
  { codigo: 'CZE', descripcion: 'República Checa' },
  { codigo: 'CHL', descripcion: 'Chile' },
  { codigo: 'CHN', descripcion: 'China' },
  { codigo: 'CYP', descripcion: 'Chipre' },
  { codigo: 'CCK', descripcion: 'Islas Cocos' },
  { codigo: 'COL', descripcion: 'Colombia' },
  { codigo: 'COM', descripcion: 'Comoras' },
  { codigo: 'COG', descripcion: 'República del Congo' },
  { codigo: 'COD', descripcion: 'República Democrática del Congo' },
  { codigo: 'COK', descripcion: 'Islas Cook' },
  { codigo: 'PRK', descripcion: 'Corea del Norte' },
  { codigo: 'KOR', descripcion: 'Corea del Sur' },
  { codigo: 'CIV', descripcion: 'Costa de Marfil' },
  { codigo: 'CRI', descripcion: 'Costa Rica' },
  { codigo: 'HRV', descripcion: 'Croacia' },
  { codigo: 'CUB', descripcion: 'Cuba' },
  { codigo: 'CUW', descripcion: 'Curazao' },
  { codigo: 'D', descripcion: 'D' },
  { codigo: 'DNK', descripcion: 'Dinamarca' },
  { codigo: 'DMA', descripcion: 'Dominica' },
  { codigo: 'DOM', descripcion: 'República Dominicana' },
  { codigo: 'E', descripcion: 'E' },
  { codigo: 'ECU', descripcion: 'Ecuador' },
  { codigo: 'EGY', descripcion: 'Egipto' },
  { codigo: 'SLV', descripcion: 'El Salvador' },
  { codigo: 'ARE', descripcion: 'Emiratos Árabes Unidos' },
  { codigo: 'ERI', descripcion: 'Eritrea' },
  { codigo: 'SVK', descripcion: 'Eslovaquia' },
  { codigo: 'SVN', descripcion: 'Eslovenia' },
  { codigo: 'ESP', descripcion: 'España' },
  { codigo: 'USA', descripcion: 'Estados Unidos' },
  { codigo: 'UMI', descripcion: 'Islas ultramarinas de Estados Unidos' },
  { codigo: 'EST', descripcion: 'Estonia' },
  { codigo: 'ETH', descripcion: 'Etiopía' },
  { codigo: 'F', descripcion: 'F' },
  { codigo: 'FRO', descripcion: 'Islas Feroe' },
  { codigo: 'PHL', descripcion: 'Filipinas' },
  { codigo: 'FIN', descripcion: 'Finlandia' },
  { codigo: 'FJI', descripcion: 'Fiyi' },
  { codigo: 'FRA', descripcion: 'Francia' },
  { codigo: 'G', descripcion: 'G' },
  { codigo: 'GAB', descripcion: 'Gabón' },
  { codigo: 'GMB', descripcion: 'Gambia' },
  { codigo: 'GEO', descripcion: 'Georgia' },
  { codigo: 'SGS', descripcion: 'Islas Georgias del Sur y Sandwich del Sur' },
  { codigo: 'GHA', descripcion: 'Ghana' },
  { codigo: 'GIB', descripcion: 'Gibraltar' },
  { codigo: 'GRD', descripcion: 'Granada' },
  { codigo: 'GRC', descripcion: 'Grecia' },
  { codigo: 'GRL', descripcion: 'Groenlandia' },
  { codigo: 'GLP', descripcion: 'Guadalupe' },
  { codigo: 'GUM', descripcion: 'Guam' },
  { codigo: 'GTM', descripcion: 'Guatemala' },
  { codigo: 'GUF', descripcion: 'Guayana Francesa' },
  { codigo: 'GGY', descripcion: 'Guernsey' },
  { codigo: 'GIN', descripcion: 'Guinea' },
  { codigo: 'GNQ', descripcion: 'Guinea Ecuatorial' },
  { codigo: 'GNB', descripcion: 'Guinea-Bissau' },
  { codigo: 'GUY', descripcion: 'Guyana' },
  { codigo: 'H', descripcion: 'H' },
  { codigo: 'HTI', descripcion: 'Haití' },
  { codigo: 'HMD', descripcion: 'Islas Heard y McDonald' },
  { codigo: 'HND', descripcion: 'Honduras' },
  { codigo: 'HKG', descripcion: 'Hong Kong' },
  { codigo: 'HUN', descripcion: 'Hungría' },
  { codigo: 'I', descripcion: 'I' },
  { codigo: 'IND', descripcion: 'India' },
  { codigo: 'IDN', descripcion: 'Indonesia' },
  { codigo: 'IRN', descripcion: 'Irán' },
  { codigo: 'IRQ', descripcion: 'Iraq' },
  { codigo: 'IRL', descripcion: 'Irlanda' },
  { codigo: 'ISL', descripcion: 'Islandia' },
  { codigo: 'ISR', descripcion: 'Israel' },
  { codigo: 'ITA', descripcion: 'Italia' },
  { codigo: 'J', descripcion: 'J' },
  { codigo: 'JAM', descripcion: 'Jamaica' },
  { codigo: 'JPN', descripcion: 'Japón' },
  { codigo: 'JEY', descripcion: 'Jersey' },
  { codigo: 'JOR', descripcion: 'Jordania' },
  { codigo: 'K', descripcion: 'K' },
  { codigo: 'KAZ', descripcion: 'Kazajistán' },
  { codigo: 'KEN', descripcion: 'Kenia' },
  { codigo: 'KGZ', descripcion: 'Kirguistán' },
  { codigo: 'KIR', descripcion: 'Kiribati' },
  { codigo: 'KWT', descripcion: 'Kuwait' },
  { codigo: 'L', descripcion: 'L' },
  { codigo: 'LAO', descripcion: 'Laos' },
  { codigo: 'LSO', descripcion: 'Lesoto' },
  { codigo: 'LVA', descripcion: 'Letonia' },
  { codigo: 'LBN', descripcion: 'Líbano' },
  { codigo: 'LBR', descripcion: 'Liberia' },
  { codigo: 'LBY', descripcion: 'Libia' },
  { codigo: 'LIE', descripcion: 'Liechtenstein' },
  { codigo: 'LTU', descripcion: 'Lituania' },
  { codigo: 'LUX', descripcion: 'Luxemburgo' },
  { codigo: 'M', descripcion: 'M' },
  { codigo: 'MAC', descripcion: 'Macao' },
  { codigo: 'MKD', descripcion: 'Macedonia' },
  { codigo: 'MDG', descripcion: 'Madagascar' },
  { codigo: 'MYS', descripcion: 'Malasia' },
  { codigo: 'MWI', descripcion: 'Malaui' },
  { codigo: 'MDV', descripcion: 'Maldivas' },
  { codigo: 'MLI', descripcion: 'Malí' },
  { codigo: 'MLT', descripcion: 'Malta' },
  { codigo: 'FLK', descripcion: 'Islas Malvinas' },
  { codigo: 'IMN', descripcion: 'Isla de Man' },
  { codigo: 'MNP', descripcion: 'Islas Marianas del Norte' },
  { codigo: 'MAR', descripcion: 'Marruecos' },
  { codigo: 'MHL', descripcion: 'Islas Marshall' },
  { codigo: 'MTQ', descripcion: 'Martinica' },
  { codigo: 'MUS', descripcion: 'Mauricio' },
  { codigo: 'MRT', descripcion: 'Mauritania' },
  { codigo: 'MYT', descripcion: 'Mayotte' },
  { codigo: 'MEX', descripcion: 'México' },
  { codigo: 'FSM', descripcion: 'Micronesia' },
  { codigo: 'MDA', descripcion: 'Moldavia' },
  { codigo: 'MCO', descripcion: 'Mónaco' },
  { codigo: 'MNG', descripcion: 'Mongolia' },
  { codigo: 'MNE', descripcion: 'Montenegro' },
  { codigo: 'MSR', descripcion: 'Montserrat' },
  { codigo: 'MOZ', descripcion: 'Mozambique' },
  { codigo: 'N', descripcion: 'N' },
  { codigo: 'NAM', descripcion: 'Namibia' },
  { codigo: 'NRU', descripcion: 'Nauru' },
  { codigo: 'CXR', descripcion: 'Isla de Navidad' },
  { codigo: 'NPL', descripcion: 'Nepal' },
  { codigo: 'NIC', descripcion: 'Nicaragua' },
  { codigo: 'NER', descripcion: 'Níger' },
  { codigo: 'NGA', descripcion: 'Nigeria' },
  { codigo: 'NIU', descripcion: 'Niue' },
  { codigo: 'NFK', descripcion: 'Norfolk' },
  { codigo: 'NOR', descripcion: 'Noruega' },
  { codigo: 'NCL', descripcion: 'Nueva Caledonia' },
  { codigo: 'NZL', descripcion: 'Nueva Zelanda' },
  { codigo: 'O', descripcion: 'O' },
  { codigo: 'OMN', descripcion: 'Omán' },
  { codigo: 'P', descripcion: 'P' },
  { codigo: 'NLD', descripcion: 'Países Bajos (Holanda)' },
  { codigo: 'PAK', descripcion: 'Pakistán' },
  { codigo: 'PLW', descripcion: 'Palaos' },
  { codigo: 'PSE', descripcion: 'Territorios palestinos' },
  { codigo: 'PAN', descripcion: 'Panamá' },
  { codigo: 'PNG', descripcion: 'Papúa Nueva Guinea' },
  { codigo: 'PRY', descripcion: 'Paraguay' },
  { codigo: 'PER', descripcion: 'Perú' },
  { codigo: 'PCN', descripcion: 'Islas Pitcairn' },
  { codigo: 'PYF', descripcion: 'Polinesia Francesa' },
  { codigo: 'POL', descripcion: 'Polonia' },
  { codigo: 'PRT', descripcion: 'Portugal' },
  { codigo: 'PRI', descripcion: 'Puerto Rico' },
  { codigo: 'Q', descripcion: 'Q' },
  { codigo: 'QAT', descripcion: 'Qatar' },
  { codigo: 'R', descripcion: 'R' },
  { codigo: 'GBR', descripcion: 'Reino Unido (Inglaterra)' },
  { codigo: 'REU', descripcion: 'Reunión' },
  { codigo: 'RWA', descripcion: 'Ruanda' },
  { codigo: 'ROU', descripcion: 'Rumania' },
  { codigo: 'RUS', descripcion: 'Rusia' },
  { codigo: 'S', descripcion: 'S' },
  { codigo: 'ESH', descripcion: 'Sahara Occidental' },
  { codigo: 'SLB', descripcion: 'Islas Salomón' },
  { codigo: 'WSM', descripcion: 'Samoa' },
  { codigo: 'ASM', descripcion: 'Samoa Americana' },
  { codigo: 'BLM', descripcion: 'San Bartolomé' },
  { codigo: 'KNA', descripcion: 'San Cristóbal y Nieves' },
  { codigo: 'SMR', descripcion: 'San Marino' },
  { codigo: 'SPM', descripcion: 'San Pedro y Miquelón' },
  { codigo: 'VCT', descripcion: 'San Vicente y las Granadinas' },
  { codigo: 'SHN', descripcion: 'Santa Helena' },
  { codigo: 'LCA', descripcion: 'Santa Lucía' },
  { codigo: 'STP', descripcion: 'Santo Tomé y Príncipe' },
  { codigo: 'SEN', descripcion: 'Senegal' },
  { codigo: 'SRB', descripcion: 'Serbia' },
  { codigo: 'SYC', descripcion: 'Seychelles' },
  { codigo: 'SLE', descripcion: 'Sierra Leona' },
  { codigo: 'SGP', descripcion: 'Singapur' },
  { codigo: 'SYR', descripcion: 'Siria' },
  { codigo: 'SOM', descripcion: 'Somalia' },
  { codigo: 'LKA', descripcion: 'Sri Lanka' },
  { codigo: 'SWZ', descripcion: 'Suazilandia' },
  { codigo: 'ZAF', descripcion: 'Sudáfrica' },
  { codigo: 'SDN', descripcion: 'Sudán' },
  { codigo: 'SWE', descripcion: 'Suecia' },
  { codigo: 'CHE', descripcion: 'Suiza' },
  { codigo: 'SUR', descripcion: 'Surinam' },
  { codigo: 'SJM', descripcion: 'Svalbard y Jan Mayen' },
  { codigo: 'T', descripcion: 'T' },
  { codigo: 'THA', descripcion: 'Tailandia' },
  { codigo: 'TWN', descripcion: 'Taiwán' },
  { codigo: 'TZA', descripcion: 'Tanzania' },
  { codigo: 'TJK', descripcion: 'Tayikistán' },
  { codigo: 'IOT', descripcion: 'Territorio Británico del Océano Índico' },
  { codigo: 'ATF', descripcion: 'Territorios Australes Franceses' },
  { codigo: 'TLS', descripcion: 'Timor Oriental' },
  { codigo: 'TGO', descripcion: 'Togo' },
  { codigo: 'TKL', descripcion: 'Tokelau' },
  { codigo: 'TON', descripcion: 'Tonga' },
  { codigo: 'TTO', descripcion: 'Trinidad y Tobago' },
  { codigo: 'TUN', descripcion: 'Túnez' },
  { codigo: 'TCA', descripcion: 'Islas Turcas y Caicos' },
  { codigo: 'TKM', descripcion: 'Turkmenistán' },
  { codigo: 'TUR', descripcion: 'Turquía' },
  { codigo: 'TUV', descripcion: 'Tuvalu' },
  { codigo: 'U', descripcion: 'U' },
  { codigo: 'UKR', descripcion: 'Ucrania' },
  { codigo: 'UGA', descripcion: 'Uganda' },
  { codigo: 'EUR', descripcion: 'Unión Europea' },
  { codigo: 'URS', descripcion: 'Unión Soviética' },
  { codigo: 'URY', descripcion: 'Uruguay' },
  { codigo: 'UZB', descripcion: 'Uzbekistán' },
  { codigo: 'V', descripcion: 'V' },
  { codigo: 'VUT', descripcion: 'Vanuatu' },
  { codigo: 'VAT', descripcion: 'Ciudad del Vaticano' },
  { codigo: 'VEN', descripcion: 'Venezuela' },
  { codigo: 'VNM', descripcion: 'Vietnam' },
  { codigo: 'VGB', descripcion: 'Islas Vírgenes Británicas' },
  { codigo: 'VIR', descripcion: 'Islas Vírgenes Estadounidenses' },
  { codigo: 'W', descripcion: 'W' },
  { codigo: 'WLF', descripcion: 'Wallis y Futuna' },
  { codigo: 'Y', descripcion: 'Y' },
  { codigo: 'YEM', descripcion: 'Yemen' },
  { codigo: 'DJI', descripcion: 'Yibuti' },
  { codigo: 'Z', descripcion: 'Z' },
  { codigo: 'ZMB', descripcion: 'Zambia' },
  { codigo: 'ZWE', descripcion: 'Zimbabue' }
];

export const getTabla9Nacionalidad = (): Tabla9Nacionalidad[] => {
  return TABLA_9_NACIONALIDAD;
};

export const getTabla9NacionalidadByCodigo = (codigo: string): Tabla9Nacionalidad | undefined => {
  return TABLA_9_NACIONALIDAD.find(item => item.codigo === codigo);
};

export const getTabla9NacionalidadDescripcion = (codigo: string): string => {
  const item = getTabla9NacionalidadByCodigo(codigo);
  return item ? item.descripcion : '';
}; 